# Generated by Django 4.2.2 on 2023-06-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_category_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='phone_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='images1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/product'),
        ),
    ]
