# Generated by Django 4.2.2 on 2023-06-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_account_street_avenue_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='block_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
